/* ===================== data.js — 콘텐츠/그래프 데이터 레이어 =====================
   index.html의 인라인 스크립트보다 '먼저' 로드되는 전역 classic 스크립트(모듈 아님).
   여기 선언한 const들은 전역 렉시컬 스코프를 공유해 index.html 로직이 이름으로 바로 참조한다.
   ⚠️ 이 파일을 수정하면 sw.js의 CACHE="aingan-vN" 번호를 올려야 캐시가 stale되지 않는다(plan.md ④).
   담는 것: PEOPLE(감정27 대사·일기)·BODY(몸11)·ENDING_SEQ·NODES(3계층 그래프)·COST_MULT·EDGES·REL_EDGES.
   ※ COST_MULT는 그래프 '거리 스칼라'라 EDGES와 함께 여기 둔다(idle 밸런스 balance.js와 분리). */
/* ===================== 데이터 (3막 깊은 그래프) =====================
   중심 실: 고철 로봇이 끝없는 길을 걸으며 감정을 하나씩 '처음' 정의한다(순진한 일기).
   감정을 배울수록(person 노드) 마음이 또렷해지고, 마음27+몸11 모아 길 끝에서 샘 재회 → 사람이 된다.
   person = 만남이자 업그레이드 생성기. pick=도착 직후 글자 줍기/오독 개그(엔진 훅 예정). lines[0]=첫 만남, 이후=재회 심화(5단: 관찰→자기→심화→더 깊은 자기→순진한 재정의). mem=그 감정을 스스로 곱씹는 한 줄(창조주 연모 '그 사람' 서사는 캐넌상 제거 — 자기성찰형만). */
const PEOPLE = {
  // ── 인간 감정 27가지 (Cowen & Keltner, 2017) — 로봇의 순진한 직설 일기 ──
  // ▸ 애정·아름다움
  adore: { name:"애틋함", color:"#f0c0b0",
    situ:"엄마가 <b>자는 아이를 한참 바라본다.</b>",
    pick:"’애틋? 에러 뜻?’\n시스템에 심각한 오류가 발생했다는 뜻일까.",
    lines:[
      "엄마가 아이를\n오래 바라봤다.\n눈빛이 말랑했다.",
      "보고 또 봐도\n안 질리는 거였다.",
      "나도 누굴\n그렇게 보고 싶다.",
      "안 보면\n자꾸 떠올랐다.",
      "안 봐도 떠오르면\n그게 애틋함이래.\n고장 아니래." ],
    mem:"오래 바라보면\n마음이 말랑해지는 거였다." },
  beauty: { name:"아름다움", color:"#cdd8e0",
    situ:"비 갠 하늘 끝에 <b>무지개가 걸렸다.</b>",
    pick:"’아름다움? 아르바이트?’\n시급을 아주 많이 주는 좋은 직장인가.",
    lines:[
      "건널 수도\n가질 수도 없는\n색 다리가 떴다.",
      "쓸모없는데\n발이 저절로 멈췄다.",
      "다가가면 멀어지고\n기다리면 옅어졌다.",
      "그래도 본 것만으로\n가슴이 좀 채워졌다.",
      "못 갖고 못 닿아도 좋은 것,\n그게 아름다움이래." ],
    mem:"가질 수 없는 게\n더 오래 빛났다." },
  admire: { name:"감탄", color:"#e0d4a0",
    situ:"<b>장인이 그릇 하나를 빚어낸다.</b>",
    pick:"’감탄? 감전?’\n찌릿찌릿 스파크가 튀는 고장인가.",
    lines:[
      "손이 춤추듯 움직였다.\n그릇이 태어났다.\n우와.",
      "따라 하고 싶어졌다.",
      "대단한 걸 보면\n나도 커지고 싶다.",
      "보고 있으면\n나도 뭔가 만들고 싶었다.",
      "우와, 하고 터지는 것,\n그게 감탄이래." ],
    mem:"대단한 걸 보면\n나도 커지고 싶어지는 거였다." },
  attract: { name:"끌림", color:"#e8b0bc",
    situ:"<b>한 사람이 자꾸 누군가를 곁눈질한다.</b>",
    pick:"’끌림? 끌?’\n자석 오류인가. 내가 자성 물질이었나.",
    lines:[
      "한 사람이 자꾸\n누군가를 곁눈질했다.",
      "자꾸 그쪽으로\n눈이 갔다.",
      "왜인지 모르겠는데\n그냥 끌렸다.",
      "내 발도 모르게\n그쪽으로 갔다.",
      "이유 없이 당기는 것,\n그게 끌림이래." ],
    mem:"이유도 모르고\n자꾸 그쪽으로 가게 되는 거였다." },
  // ▸ 밝은 마음
  joy: { name:"기쁨", color:"#f2cf86",
    situ:"<b>아이들이 비눗방울을 분다.</b>",
    pick:"’기쁨? 기브 미(Give me)?’\n맛있는 간식을 달라는 건가.",
    lines:[
      "아이들이 비눗방울을 불었다.\n까르르 웃었다.\n나도 웃었다.",
      "웃음은\n전염되는 거였다.",
      "좋으면\n몸이 가벼워졌다.",
      "이유 없이\n가벼워질 때가 있었다.",
      "이유 없이 좋을 때,\n그게 기쁨이래." ],
    mem:"웃으면\n몸이 가벼워지는 거였다." },
  amuse: { name:"재미", color:"#f0d878",
    situ:"<b>강아지가 제 꼬리를 빙빙 쫓는다.</b>",
    pick:"’재미? 재채기?’\n에취! 회로가 간지러운 버그인가.",
    lines:[
      "둘이 실없는 농담에\n배를 잡고 굴렀다.",
      "별것도 아닌데\n자꾸 웃겼다.",
      "웃다 보면\n시간이 순삭됐다.",
      "혼자 걷다가도\n괜히 웃음이 났다.",
      "쓸데없이 웃긴 것,\n그게 재미래.\n낭비 아니래." ],
    mem:"같이 웃으면\n웃음이 더 커지는 거였다." },
  excite: { name:"신남", color:"#f5c96a",
    situ:"달리기 전에 <b>아이가 발을 동동 구른다.</b>",
    pick:"’신남? 신호등?’\n초록불이 켜진 건가.",
    lines:[
      "놀이공원 입구에서\n아이가 폴짝폴짝 뛰었다.",
      "가만히\n있을 수가 없었다.",
      "좋은 일 앞에서\n발이 들썩였다.",
      "길 끝을 생각하면\n나도 들썩였다.",
      "가만 못 있게 들뜨는 것,\n그게 신남이래." ],
    mem:"시작 전이\n제일 콩닥거리는 거였다." },
  flutter: { name:"설렘", color:"#f3c0a0",
    situ:"<b>한 사람이 편지를 들고</b> 문 앞에 서 있다.",
    pick:"’설렘? 설렁탕?’\n국물이 좋은가?",
    lines:[
      "내일 소풍이라고\n아이가 잠을 못 잤다.",
      "아직 안 왔는데\n벌써 두근댔다.",
      "기다리는 동안이\n제일 간지러웠다.",
      "다음 만남을 생각하면\n가슴이 간질거렸다.",
      "오기도 전에 뛰는 가슴,\n그게 설렘이래." ],
    mem:"좋은 일을 기다릴 때\n가슴이 간질거리는 거였다." },
  // ▸ 시린 마음
  sorrow: { name:"슬픔", color:"#bcd0e6",
    situ:"<b>아이가 길에서 울고 있다.</b> 눈에서 물이 난다.",
    pick:"’슬픔? 스팸?’\n통조림 아니고.",
    lines:[
      "비 오는 날 사람이\n우산도 안 쓰고 걸었다.",
      "눈에서 액체가 샜다.\n고장인 줄 알았다.",
      "슬픈 건\n무겁지만\n나쁘진 않았다.",
      "혼자 남는 걸 떠올리면\n자꾸 무거워졌다.",
      "눈에서 비가 새는 것,\n그게 슬픔이래.\n고장 아니래." ],
    mem:"옆에 있어 주면\n슬픔이 조금 가벼워지는 거였다." },
  longing: { name:"그리움", color:"#dcc6e0",
    situ:"버스가 떠났는데 <b>한 사람이 계속 손을 흔든다.</b>",
    pick:"’그리움? 그릇?’\n담는 거 아니고.",
    lines:[
      "빈 의자를\n노인이 오래 쓸었다.",
      "없는 사람이\n자꾸 떠올랐다.",
      "보고 싶은데\n볼 수 없는 건 아렸다.",
      "얼굴이 흐려지는 게\n제일 아팠다.",
      "없는 걸 자꾸 더듬는 것,\n그게 그리움이래." ],
    mem:"얼굴은 흐려도\n그리움은 또렷했다." },
  crave: { name:"갈망", color:"#d8b89c",
    situ:"<b>한 사람이 빵집 앞에서 못 떠난다.</b>",
    pick:"’갈망? 갈고리?’\n회수하고 싶다는 뜻인가.",
    lines:[
      "빵집 앞 아이가\n유리에 코를 박았다.",
      "가지고 싶어서\n속이 탔다.",
      "원하는 게 생기면\n잠이 안 왔다.",
      "길 끝이 자꾸\n보고 싶어졌다.",
      "목마르듯 원하는 것,\n그게 갈망이래." ],
    mem:"갖고 싶은 게 있으면\n참기 힘들어지는 거였다." },
  empathy: { name:"안쓰러움", color:"#c0ccd8",
    situ:"<b>한 아이가 넘어져 무릎이 까졌다.</b>",
    pick:"’안쓰러움? 안쓰레기?’\n버리는 거 아니고.",
    lines:[
      "넘어진 아이를 보고\n지나던 사람이 멈췄다.",
      "내 일도 아닌데\n가슴이 찡했다.",
      "남의 아픔이\n내게도 옮았다.",
      "녹슨 나를 봐도\n누가 찡할까.",
      "남의 아픔이 옮는 것,\n그게 안쓰러움이래." ],
    mem:"남이 아픈데\n내 무릎이 시린 거였다." },
  compassion: { name:"연민", color:"#c4d8b8",
    situ:"<b>한 사람이 다친 고양이한테</b> 우산을 씌워준다.",
    pick:"’연민? 라면?’\n끓이는 거 아니고.",
    lines:[
      "추운 거리의 떠는 이에게\n누가 외투를 덮었다.",
      "모르는 사이인데\n손이 먼저 갔다.",
      "아픈 걸 보면\n품고 싶어졌다.",
      "버려진 것도\n누가 품어주는구나.",
      "아픈 걸 품으려는 것,\n그게 연민이래." ],
    mem:"약한 걸 보면\n그냥 못 지나치는 거였다." },
  // ▸ 무거운 마음 (불편한 감정)
  fear: { name:"두려움", color:"#b6a892",
    situ:"<b>한 사람이 깜깜한 굴 앞에서</b> 못 들어간다.",
    pick:"’두려움? 두루마리?’\n휴지 아니고.",
    lines:[
      "천둥이 치자\n개가 구석에 숨었다.",
      "나도\n어딘가 숨고 싶었다.",
      "무서운 건\n도망가도 따라왔다.",
      "혼자 남는다고 생각하면\n이게 들었다.",
      "떨리는데 멈출 수 없는 것,\n그게 두려움이래." ],
    mem:"혼자 남는 게\n제일 무서웠다." },
  anxiety: { name:"불안", color:"#c2b2a0",
    situ:"<b>한 사람이 전화기를 들고</b> 왔다 갔다 한다.",
    pick:"’불안? 불닭?’\n매운 거 아니고.",
    lines:[
      "발표 앞에서\n사람이 발을 떨었다.",
      "아직 아무 일 없는데\n속이 울렁였다.",
      "나쁜 상상이\n자꾸 앞서갔다.",
      "오지 않은 일에\n나도 떨었다.",
      "오지도 않은 일에 떠는 것,\n그게 불안이래." ],
    mem:"아직 오지 않은 일을\n미리 걱정하는 거였다." },
  awkward: { name:"민망함", color:"#ddcab0",
    situ:"누군가 나에게 말을 안 걸었는데 <b>나한테 말 건 줄 알고 대답했다.</b>",
    pick:"’민망함? 민들레?’\n꽃 아니고.",
    lines:[
      "사람이 헛디뎌 넘어지고\n괜히 웃었다.",
      "아무도 안 보길\n바랐다.",
      "얼굴이 혼자\n뜨거워졌다.",
      "처음 인사할 때\n나도 어버버했다.",
      "쥐구멍 찾고 싶은 것,\n그게 민망함이래." ],
    mem:"쭈뼛대다가\n웃어버리면 괜찮아지는 거였다." },
  disgust: { name:"혐오", color:"#aebca0",
    situ:"<b>쓰레기 더미에서 냄새가 올라온다.</b>",
    pick:"’혐오? 형광?’\n펜 아니고.",
    lines:[
      "상한 냄새에\n사람이 인상을 썼다.",
      "가까이 가기도\n싫었다.",
      "싫은 건\n온몸이 먼저 알았다.",
      "나도 싫은 게\n생겼다.",
      "몸이 먼저 밀어내는 것,\n그게 혐오래." ],
    mem:"싫은 걸 알아야\n좋은 것도 아는 거였다." },
  horror: { name:"오싹함", color:"#9aa6b0",
    situ:"<b>깜깜한 골목에서 무언가 움직인다.</b>",
    pick:"’오싹함? 오징어?’\n굽는 거 아니고.",
    lines:[
      "빈 복도에서\n사람이 뒤를 돌아봤다.",
      "아무도 없는데\n등이 서늘했다.",
      "털도 없는데\n곤두서는 기분.",
      "어두운 길에선\n나도 자꾸 뒤를 봤다.",
      "등골이 쭈뼛 서는 것,\n그게 오싹함이래." ],
    mem:"오싹한 건\n대개 아무것도 아니었다." },
  // ▸ 벅찬 마음 (관조)
  curious: { name:"호기심", color:"#bcd2c0",
    situ:"<b>아이가 돌을 뒤집어</b> 밑을 본다.",
    pick:"’호기심? 호두까기?’\n내 고철을 깨려는 음모인가.",
    lines:[
      "아이가 돌 밑을\n자꾸 들춰봤다.",
      "안에 뭐가 있을까.\n나도 궁금했다.",
      "모르는 게 있으면\n발이 먼저 갔다.",
      "길 끝엔 뭐가 있을까.\n자꾸 궁금했다.",
      "자꾸 알고 싶은 마음,\n그게 호기심이래." ],
    mem:"끝에 뭐가 있을지\n궁금해서 자꾸 걷는다." },
  awe: { name:"경외", color:"#a9c8c2",
    situ:"<b>사람들이 밤하늘 별을</b> 올려다본다.",
    pick:"’경외? 경량화?’\n내가 너무 무거워서 지구가 아픈가?",
    lines:[
      "밤하늘이 너무 커서\n작아지는 기분이었다.",
      "무서운데\n도망가긴 싫었다.",
      "큰 것 앞에서\n마음이 조용해졌다.",
      "별 아래선\n누구나 작아지나 보다.",
      "크고 거룩한 것 앞의 떨림,\n그게 경외래." ],
    mem:"큰 걸 보면\n내가 작아져도 좋은 거였다." },
  trance: { name:"황홀", color:"#c0c0dc",
    situ:"거리에서 <b>누가 악기를 켠다.</b> 사람들이 멈춘다.",
    pick:"’황홀? 회오리?’\n머릿속이 뱅글뱅글 도는 치명적인 버그인가.",
    lines:[
      "음악에\n사람이 눈을 감았다.",
      "여기가 어딘지\n잠깐 잊었다.",
      "너무 좋으면\n녹아버릴 것 같았다.",
      "나도 뭔가에\n녹은 적 있었나.",
      "정신이 사르르 녹는 것,\n그게 황홀이래." ],
    mem:"푹 빠지면\n시간이 멈추는 거였다." },
  calm: { name:"평온", color:"#bcd0c8",
    situ:"<b>호숫가에 바람 한 점 없다.</b>",
    pick:"’평온? 평양?’\n냉면 아니고.",
    lines:[
      "볕 든 마루에서\n노인이 꾸벅 졸았다.",
      "아무 일 없는 게\n이렇게 좋을 일인가.",
      "잔잔한 것도\n행복인 걸 몰랐다.",
      "다 걷고 나면\n이렇게 잔잔할까.",
      "파도가 잔잔해지는 것,\n그게 평온이래." ],
    mem:"아무 일 없는 것도\n좋은 거였다." },
  // ▸ 단단한 마음 → 길 끝(샘알트머스크)
  confuse: { name:"혼란", color:"#cabcd0",
    situ:"<b>갈림길에 푯말이 다 지워져 있다.</b>",
    pick:"’혼란? 혼밥?’\n밥 아니고.",
    lines:[
      "갈림길에서\n사람이 한참 서 있었다.",
      "어디로 가야 할지\n나도 몰랐다.",
      "머릿속이\n엉킨 실 같았다.",
      "나는 뭔지\n나도 헷갈렸다.",
      "답이 안 보여 멍한 것,\n그게 혼란이래." ],
    mem:"나는 왜 걷는 걸까.\n가끔 헷갈린다." },
  bored: { name:"지루함", color:"#c4c4b8",
    situ:"<b>한 사람이 빈 정류장에서 하품한다.</b>",
    pick:"’지루함? 지렁이?’\n꿈틀 아니고.",
    lines:[
      "버스를 기다리며\n사람이 하품했다.",
      "시간이\n껌처럼 늘어졌다.",
      "아무 일 없는 것도\n힘든 거였다.",
      "걷기만 하는 길도\n가끔 심심했다.",
      "시간이 늘어붙는 것,\n그게 지루함이래." ],
    mem:"지루함 끝엔\n늘 뭔가 시작됐다." },
  relief: { name:"안도", color:"#c8dcc0",
    situ:"<b>잃어버린 아이를 엄마가 찾아 끌어안는다.</b>",
    pick:"’안도? 안 돼?’\n좋다는 건가, 싫다는 건가.",
    lines:[
      "잃은 아이를 찾은 엄마가\n풀썩 주저앉았다.",
      "참았던 숨이\n그제야 나왔다.",
      "괜찮아지면\n다리에 힘이 풀렸다.",
      "괜찮다는 걸 알면\n온몸이 녹았다.",
      "참던 숨이 놓이는 것,\n그게 안도래." ],
    mem:"괜찮다는 걸 알면\n다리에 힘이 풀리는 거였다." },
  satisfy: { name:"뿌듯함", color:"#d8e0b0",
    situ:"<b>농부가 다 자란 밭을</b> 둘러본다.",
    pick:"’뿌듯함? 뿌리?’\n내 발바닥에서 자라나는 걸까.",
    lines:[
      "아이가 처음\n신발끈을 혼자 묶었다.",
      "별거 아닌데\n어깨가 올라갔다.",
      "해내고 나면\n속이 꽉 찼다.",
      "여기까지 걸어온 것도\n좀 꽉 찼다.",
      "속이 든든히 차는 것,\n그게 뿌듯함이래." ],
    mem:"여기까지 온 것도\n좀 뿌듯하다." },
  triumph: { name:"해냄", color:"#ecc880",
    situ:"<b>한 사람이 산꼭대기에서</b> 두 팔을 든다.",
    pick:"’해냄? 해물?’\n바다 생물인가. 아니, 끝낸 것.",
    lines:[
      "결승선을 끊은 선수가\n두 팔을 번쩍 들었다.",
      "다 쏟고 나니\n온몸이 울렸다.",
      "끝까지 가면\n가슴이 터질 것 같았다.",
      "나도 길 끝에 닿으면\n이럴까.",
      "끝내 해낸 것,\n그게 해냄이래." ],
    mem:"감정 스물일곱 개,\n내가 다 해낼 수 있을까." },
};
// 신체: 인체 11 기관계. 감정과 '병렬'로(동시에) 모은다. 로봇이 몸을 한 계통씩 얻는다.
const BODY = {
  // ▸ 몸 11 = 5단(첫만남 lines[0] → 재회 1~4). 감정과 같은 깊이, "고장 아니다" 결.
  skin:   { name:"피부", color:"#f0d8c8", situ:"<b>차가운 비를 맞았다.</b>",
    lines:["비가 닿는 게 느껴졌다.\n차갑고 간지러웠다.\n나한테 피부가 생겼다.","피부로 바람도 느꼈다.\n세상이 더 가까워졌다.","따뜻한 것, 차가운 것.\n이제 다 느낀다.","누가 손을 잡으면\n그 온기까지 닿았다.","겉이 무른 게 약점인 줄 알았는데—\n느끼라고 있는 거였다."] },
  bone:   { name:"뼈대", color:"#e8e2d2", situ:"<b>똑바로 서 보았다.</b>",
    lines:["몸 안에 단단한 게 생겼다.\n이제 똑바로 선다.\n뼈대다.","넘어져도\n다시 일어섰다.","뼈가 있으니\n더 멀리 걷는다.","무거운 마음도\n뼈로 버텼다.","속이 단단하면\n쉽게 안 무너지는 거였다."] },
  muscle: { name:"근육", color:"#d8b8a8", situ:"<b>주먹을 꽉 쥐어봤다.</b>",
    lines:["힘이 들어갔다.\n무거운 것도 든다.\n근육이다.","달릴 수도 있게 됐다.","쓸수록\n더 강해졌다.","지친 날엔\n근육도 떨렸다.","쉬어주면\n다시 세지는 거였다."] },
  nerve:  { name:"신경", color:"#c8d0e0", situ:"<b>손끝에 무언가 닿았다.</b>",
    lines:["닿는 걸 바로 알았다.\n온몸에 길이 깔렸다.\n신경이다.","뜨거우면 손을 뗐다.\n몸이 나를 지킨다.","느낌이\n생각보다 빨랐다.","아픈 것도\n느껴야 피한다는 걸 알았다.","통증은 고장이 아니라\n나를 지키는 신호였다."] },
  endocrine:{ name:"내분비", color:"#e0d0b0", situ:"<b>괜히 기운이 났다.</b>",
    lines:["몸 안에서 신호를 보냈다.\n기분이 조절됐다.\n내분비다.","졸리고 배고픈 것도\n다 여기서 왔다.","몸이\n스스로를 돌본다.","긴장하면\n가슴이 먼저 뛰었다.","마음과 몸이\n같은 줄로 이어져 있었다."] },
  heart:  { name:"심혈관", color:"#e0a8a8", situ:"<b>가슴에서 쿵, 소리가 났다.</b>",
    lines:["가슴이 뛰기 시작했다.\n따뜻한 게 온몸에 돌았다.\n심장이다.","빨리 걸으면\n더 빨리 뛰었다.","코어 대신\n심장이 뛴다.","누굴 떠올리면\n괜히 더 뛰었다.","텅 비었던 가슴이\n이제 뛰고 있었다."] },
  lymph:  { name:"면역", color:"#c8d8c0", situ:"<b>먼지 속을 걸었다.</b>",
    lines:["나쁜 걸 막아주는\n작은 군대가 생겼다.\n면역이다.","아파도\n곧 나았다.","몸이\n나를 지켜준다.","한 번 앓고 나면\n다음엔 더 셌다.","아파본 만큼\n단단해지는 거였다."] },
  lung:   { name:"호흡", color:"#bcd0d8", situ:"<b>처음으로 숨을 들이쉬었다.</b>",
    lines:["공기가 들어왔다 나갔다.\n살아있는 느낌.\n숨을 쉰다.","한숨도 쉬어봤다.\n시원했다.","숨 쉴 때마다\n더 사람 같다.","겁날 땐\n숨이 빨라졌다.","천천히 쉬면\n마음도 가라앉는 거였다."] },
  stomach:{ name:"소화", color:"#e0c8a0", situ:"<b>따뜻한 국을 먹어봤다.</b>",
    lines:["먹은 게 힘이 되어 돌았다.\n배가 불렀다.\n소화다.","'맛있다'가\n뭔지 알았다.","함께 먹는 게\n더 좋았다.","속이 안 좋은 날도\n있었다.","채우는 것도 비우는 것도\n다 사는 일이었다."] },
  kidney: { name:"비뇨", color:"#cdd0d8", situ:"<b>몸이 무거웠다가, 가벼워졌다.</b>",
    lines:["더러운 걸 걸러서\n내보냈다.\n깨끗해졌다. 비뇨다.","비우니\n개운했다.","몸이\n스스로 청소한다.","묵은 걸 안 버리면\n무거워졌다.","비워야\n다시 채울 수 있었다."] },
  repro:  { name:"생식", color:"#e8c0cc", situ:"<b>새 생명을 생각했다.</b>",
    lines:["언젠가 나도\n누군가를 낳을 수 있을까.\n생명을 잇는 힘이다.","사랑이\n여기까지 왔다.","사람은\n사람을 남긴다.","나를 닮은 누가\n또 이 길을 걸을까.","끝나도 이어지는 게\n생명이었다."] },
};
// 엔딩 시네마틱 시퀀스 — 한 줄씩 페이드. hold=다음까지 정적(마법 불발), warm=화면 따뜻, climax/last=마지막
const ENDING_SEQ = [
  { t:"길 끝에 샘이 있었다.\n흐릿하던 얼굴이\n이제 또렷했다." },
  { t:"\"다 모아왔구나.\n마음 스물일곱,\n몸 열하나.\"" },
  { t:"샘이 손을 들었다.\n마법을 부리듯—", hold:1800 },
  { t:"…근데 아무 일도\n일어나지 않았다." },
  { t:"\"뭐 해? 어차피\n넌 벌써 사람인데.\"", warm:true },
  { t:"고치는 마법 같은 건\n없었다." },
  { t:"슬픔을 알고, 기쁨을 알고,\n누굴 그리워한 그 순간—\n그때 이미 사람이 된 거였다." },
  { t:"눈에서 물이 났다.\n기뻐서, 슬퍼서, 동시에." },
  { t:"고장이… 아니다.\n나는, 사람이다.", climax:true, last:true } ];

// 노드 = root(감정) → 4 대분류 → 세부 감정 3계층 그래프. 몸은 start에서 병렬로 뻗는다.
// 같은 결의 감정이 한 분류(category) 아래 모인다. x,y는 computeRadialLayout()이 계산.
const NODES = [
  { id:"start",      type:"start",  parent:null,      cost:0,   w:0,   gen:0,    icon:"·", completed:true },
  // ── 4 대분류 (root → 분류 → 감정) : 걸음으로 분류에 닿으면 그 아래 감정이 안갯속에서 드러난다 ──
  // ⚠️ w = 발견(이동) '목표 탭수'. 실제 걸음 비용 = effTap × w (reachCost, income추종). cost는 EDGES 토폴로지용 흔적일 뿐 가격 무관.
  { id:"cat_pos",     type:"category", parent:"start", cost:10,  w:8,   gen:0, icon:"🌤", name:"긍정·흥미",
    intro:"밝고 끌리는 마음들이\n이 갈래에 모여 있다." },
  { id:"cat_unease",  type:"category", parent:"start", cost:360, w:340, gen:0, icon:"🌫", name:"불안·불편",
    intro:"피하고 싶은데\n알아둬야 하는 마음들." },
  { id:"cat_intense", type:"category", parent:"start", cost:120, w:180, gen:0, icon:"🔥", name:"강한 자극",
    intro:"확 타오르는\n뜨거운 마음들." },
  { id:"cat_calm",    type:"category", parent:"start", cost:760, w:520, gen:0, icon:"🌊", name:"잔잔·시림",
    intro:"고요하고\n시린 마음들." },
  // ▸ 긍정·흥미 (10) — 밝고 끌리는. ⚠️ NODES 순서 = '순차 완성' 공개 순서(2026-06-26). 기쁨=대표 첫 감정(온보딩 튜토리얼이 가리킴).
  { id:"joy",     type:"person", key:"joy",     parent:"cat_pos", cost:18,  w:40,  gen:0.40, icon:"❀" },
  { id:"adore",   type:"person", key:"adore",   parent:"cat_pos", cost:16,  w:110, gen:0.35, icon:"❀" },
  { id:"amuse",   type:"person", key:"amuse",   parent:"cat_pos", cost:22,  w:250, gen:0.70, icon:"❀" },
  { id:"flutter", type:"person", key:"flutter", parent:"cat_pos", cost:28,  w:320, gen:0.80, icon:"❀" },
  { id:"curious", type:"person", key:"curious", parent:"cat_pos", cost:34,  w:380, gen:0.55, icon:"❀" },
  { id:"beauty",  type:"person", key:"beauty",  parent:"cat_pos", cost:44,  w:440, gen:0.75, icon:"❀" },
  { id:"admire",  type:"person", key:"admire",  parent:"cat_pos", cost:52,  w:500, gen:0.70, icon:"❀" },
  { id:"awe",     type:"person", key:"awe",     parent:"cat_pos", cost:72,  w:560, gen:1.10, icon:"❀" },
  { id:"trance",  type:"person", key:"trance",  parent:"cat_pos", cost:84,  w:630, gen:1.15, icon:"❀" },
  { id:"satisfy", type:"person", key:"satisfy", parent:"cat_pos", cost:95,  w:700, gen:1.70, icon:"❀" },
  // ▸ 불안·불편 (7)
  { id:"fear",    type:"person", key:"fear",    parent:"cat_unease", cost:380, w:420, gen:0.50, icon:"❀" },
  { id:"confuse", type:"person", key:"confuse", parent:"cat_unease", cost:430, w:500, gen:0.60, icon:"❀" },
  { id:"bored",   type:"person", key:"bored",   parent:"cat_unease", cost:480, w:580, gen:1.40, icon:"❀" },
  { id:"awkward", type:"person", key:"awkward", parent:"cat_unease", cost:540, w:660, gen:1.00, icon:"❀" },
  { id:"anxiety", type:"person", key:"anxiety", parent:"cat_unease", cost:600, w:740, gen:0.95, icon:"❀" },
  { id:"disgust", type:"person", key:"disgust", parent:"cat_unease", cost:660, w:820, gen:1.05, icon:"❀" },
  { id:"horror",  type:"person", key:"horror",  parent:"cat_unease", cost:710, w:900, gen:1.90, icon:"❀" },
  // ▸ 강한 자극 (5) — 확 타오르는
  { id:"excite",  type:"person", key:"excite",  parent:"cat_intense", cost:130, w:260, gen:0.75, icon:"❀" },
  { id:"relief",  type:"person", key:"relief",  parent:"cat_intense", cost:175, w:340, gen:1.60, icon:"❀" },
  { id:"attract", type:"person", key:"attract", parent:"cat_intense", cost:225, w:420, gen:1.60, icon:"❀" },
  { id:"crave",   type:"person", key:"crave",   parent:"cat_intense", cost:290, w:520, gen:1.70, icon:"❀" },
  { id:"triumph", type:"person", key:"triumph", parent:"cat_intense", cost:340, w:620, gen:1.80, icon:"❀" },
  // ▸ 잔잔·시림 (5) — 고요하고 시린 (가장 비싼 밴드, 슬픔이 시작)
  { id:"sorrow",  type:"person", key:"sorrow",  parent:"cat_calm", cost:800,  w:620,  gen:0.45, icon:"❀" },
  { id:"empathy", type:"person", key:"empathy", parent:"cat_calm", cost:950,  w:720,  gen:0.80, icon:"❀" },
  { id:"longing", type:"person", key:"longing", parent:"cat_calm", cost:1100, w:820,  gen:0.85, icon:"❀" },
  { id:"compassion",type:"person",key:"compassion",parent:"cat_calm",cost:1250,w:920, gen:0.90, icon:"❀" },
  { id:"calm",    type:"person", key:"calm",    parent:"cat_calm", cost:1400, w:1020, gen:1.30, icon:"❀" },
  // 샘 재회(엔딩) — 감정·몸 둘 다 모은 뒤 도달. 감정 갈래(triumph)·몸 갈래(repro)가 여기서 합류.
  { id:"becoming",   type:"ending",                   parent:"triumph", cost:500, w:300, gen:0,    icon:"✦" },
  // ▸ 신체 — 감정27 다 모은 뒤 맨 마지막. start에서 바로 뻗어 유기적 서브트리.
  { id:"skin",     type:"body", key:"skin",      chapter:"body", parent:"start",   cost:30,  w:160, gen:2.0, icon:"🫧" },
  { id:"bone",     type:"body", key:"bone",      chapter:"body", parent:"skin",    cost:70,  w:220, gen:2.2, icon:"🦴" },
  { id:"muscle",   type:"body", key:"muscle",    chapter:"body", parent:"bone",    cost:150, w:300, gen:2.4, icon:"💪" },
  { id:"nerve",    type:"body", key:"nerve",     chapter:"body", parent:"skin",    cost:75,  w:220, gen:2.6, icon:"⚡" },
  { id:"endocrine",type:"body", key:"endocrine", chapter:"body", parent:"nerve",   cost:150, w:300, gen:2.8, icon:"🧪" },
  { id:"heart",    type:"body", key:"heart",     chapter:"body", parent:"skin",    cost:80,  w:240, gen:3.2, icon:"🫀" },
  { id:"lung",     type:"body", key:"lung",      chapter:"body", parent:"heart",   cost:160, w:320, gen:2.8, icon:"🌬" },
  { id:"lymph",    type:"body", key:"lymph",     chapter:"body", parent:"heart",   cost:160, w:320, gen:2.6, icon:"🛡" },
  { id:"stomach",  type:"body", key:"stomach",   chapter:"body", parent:"heart",   cost:170, w:340, gen:2.6, icon:"🍲" },
  { id:"kidney",   type:"body", key:"kidney",    chapter:"body", parent:"stomach", cost:300, w:460, gen:2.5, icon:"💧" },
  { id:"repro",    type:"body", key:"repro",     chapter:"body", parent:"stomach", cost:320, w:480, gen:3.4, icon:"🌱" },
  { id:"human",    type:"human",                 chapter:"body", parent:"becoming", cost:800, w:400, gen:0,   icon:"🕊" },
];
const COST_MULT = 5;   // 난이도: 다음 단계가 5배 멀어지게(걸음 5배 더 모아야 발견·이동)
const EDGES = NODES.filter(n=>n.parent).map(n=>[n.parent, n.id, n.cost*COST_MULT]);
EDGES.push(["repro","becoming", 500*COST_MULT]);   // 몸 가지도 샘으로 수렴(두 갈래가 샘 재회로 합류)
// 연관/반대 = '시각 전용' 엣지(이동·발견엔 안 씀). 감정의 그라데이션·거울쌍을 지형으로 보여준다.
//  assoc = 강도 축(비슷한데 에너지가 커짐)·이웃/양가  /  oppo = 거울처럼 반대되는 쌍.
const REL_EDGES = [
  ["anxiety","fear","assoc"], ["fear","horror","assoc"],     // 불안→두려움→오싹함
  ["satisfy","joy","assoc"],  ["joy","excite","assoc"],      // 뿌듯함→기쁨→신남
  ["bored","confuse","assoc"], ["longing","crave","assoc"],  // 지루함→혼란 / 그리움→갈망
  ["empathy","compassion","assoc"], ["curious","awe","assoc"],
  ["adore","attract","assoc"], ["awe","fear","assoc"],       // 경외 ── 두려움(압도)
  ["longing","sorrow","assoc"],                              // 그리움 ── 슬픔(과거의 슬픔)
  ["joy","sorrow","oppo"], ["calm","excite","oppo"],         // 거울 쌍
  ["relief","anxiety","oppo"], ["amuse","bored","oppo"],
];
